// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AperitivoDocumentDataSlicesSlice = AperitivoSlice;

/**
 * Content for Aperitivo documents
 */
interface AperitivoDocumentData {
  /**
   * Slice Zone field in *Aperitivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AperitivoDocumentDataSlicesSlice>;
}

/**
 * Aperitivo document from Prismic
 *
 * - **API ID**: `aperitivo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AperitivoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AperitivoDocumentData>,
    "aperitivo",
    Lang
  >;

type BevandeDocumentDataSlicesSlice = BevandeSlice;

/**
 * Content for Bevande documents
 */
interface BevandeDocumentData {
  /**
   * Slice Zone field in *Bevande*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BevandeDocumentDataSlicesSlice>;
}

/**
 * Bevande document from Prismic
 *
 * - **API ID**: `bevande`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BevandeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BevandeDocumentData>,
    "bevande",
    Lang
  >;

type BirreDocumentDataSlicesSlice = BirreSlice | BirreInfoSlice;

/**
 * Content for Birre documents
 */
interface BirreDocumentData {
  /**
   * Slice Zone field in *Birre*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BirreDocumentDataSlicesSlice>;
}

/**
 * Birre document from Prismic
 *
 * - **API ID**: `birre`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BirreDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BirreDocumentData>, "birre", Lang>;

type ConclusioneMenuDocumentDataSlicesSlice = ConclusioneMenuSlice;

/**
 * Content for Conclusione menu documents
 */
interface ConclusioneMenuDocumentData {
  /**
   * Slice Zone field in *Conclusione menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: conclusione_menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ConclusioneMenuDocumentDataSlicesSlice>;
}

/**
 * Conclusione menu document from Prismic
 *
 * - **API ID**: `conclusione_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConclusioneMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConclusioneMenuDocumentData>,
    "conclusione_menu",
    Lang
  >;

type ContattiDocumentDataSlicesSlice = PrenotaTavoloSlice;

/**
 * Content for Contatti documents
 */
interface ContattiDocumentData {
  /**
   * Slice Zone field in *Contatti*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContattiDocumentDataSlicesSlice> /**
   * Meta Title field in *Contatti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contatti.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contatti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contatti.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contatti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contatti document from Prismic
 *
 * - **API ID**: `contatti`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContattiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContattiDocumentData>,
    "contatti",
    Lang
  >;

type DrinklistDocumentDataSlicesSlice = DrinkListSlice;

/**
 * Content for DrinkList documents
 */
interface DrinklistDocumentData {
  /**
   * Slice Zone field in *DrinkList*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: drinklist.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DrinklistDocumentDataSlicesSlice>;
}

/**
 * DrinkList document from Prismic
 *
 * - **API ID**: `drinklist`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DrinklistDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DrinklistDocumentData>,
    "drinklist",
    Lang
  >;

type FerozaDocumentDataSlicesSlice =
  | SimurghSlice
  | FerozaSlice
  | HeroSlice
  | SezioniHomeSlice;

/**
 * Content for Feroza documents
 */
interface FerozaDocumentData {
  /**
   * Slice Zone field in *Feroza*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FerozaDocumentDataSlicesSlice> /**
   * Meta Title field in *Feroza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: feroza.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Feroza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: feroza.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Feroza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Feroza document from Prismic
 *
 * - **API ID**: `feroza`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FerozaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FerozaDocumentData>, "feroza", Lang>;

type FooterDocumentDataSlicesSlice = LogoSlice | InfoFooterSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = MenuSlice | LogoSlice;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type InfofinalivinobirraDocumentDataSlicesSlice = InfoFinaliBirreVinoSlice;

/**
 * Content for InfoFinaliVinoBirra documents
 */
interface InfofinalivinobirraDocumentData {
  /**
   * Slice Zone field in *InfoFinaliVinoBirra*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: infofinalivinobirra.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InfofinalivinobirraDocumentDataSlicesSlice>;
}

/**
 * InfoFinaliVinoBirra document from Prismic
 *
 * - **API ID**: `infofinalivinobirra`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InfofinalivinobirraDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InfofinalivinobirraDocumentData>,
    "infofinalivinobirra",
    Lang
  >;

type MenuDocumentDataSlicesSlice = NavigazioneMenuSlice;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Slice Zone field in *Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MenuDocumentDataSlicesSlice> /**
   * Meta Title field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: menu.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: menu.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PiattomultiDocumentDataSlicesSlice =
  | RipetibileMenuSlice
  | InfoPiattoMultiSlice;

/**
 * Content for PiattoMulti documents
 */
interface PiattomultiDocumentData {
  /**
   * Slice Zone field in *PiattoMulti*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: piattomulti.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PiattomultiDocumentDataSlicesSlice>;
}

/**
 * PiattoMulti document from Prismic
 *
 * - **API ID**: `piattomulti`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PiattomultiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PiattomultiDocumentData>,
    "piattomulti",
    Lang
  >;

type ViniDocumentDataSlicesSlice = ViniInfoSlice | ViniSlice;

/**
 * Content for Vini documents
 */
interface ViniDocumentData {
  /**
   * Slice Zone field in *Vini*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ViniDocumentDataSlicesSlice>;
}

/**
 * Vini document from Prismic
 *
 * - **API ID**: `vini`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ViniDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ViniDocumentData>, "vini", Lang>;

export type AllDocumentTypes =
  | AperitivoDocument
  | BevandeDocument
  | BirreDocument
  | ConclusioneMenuDocument
  | ContattiDocument
  | DrinklistDocument
  | FerozaDocument
  | FooterDocument
  | HeaderDocument
  | InfofinalivinobirraDocument
  | MenuDocument
  | PiattomultiDocument
  | ViniDocument;

/**
 * Item in *Aperitivo → Default → Primary → Bevande*
 */
export interface AperitivoSliceDefaultPrimaryNomeBevandaItem {
  /**
   * Nome bevanda field in *Aperitivo → Default → Primary → Bevande*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.nome_bevanda[].nome_bevanda
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_bevanda: prismic.KeyTextField;

  /**
   * Icona field in *Aperitivo → Default → Primary → Bevande*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.nome_bevanda[].icona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona: prismic.ImageField<never>;
}

/**
 * Item in *Aperitivo → Default → Primary → Salse*
 */
export interface AperitivoSliceDefaultPrimarySalseItem {
  /**
   * Nome salsa field in *Aperitivo → Default → Primary → Salse*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.salse[].nome_salsa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_salsa: prismic.KeyTextField;

  /**
   * Vegetariano field in *Aperitivo → Default → Primary → Salse*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.salse[].vegetariano
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vegetariano: prismic.ImageField<never>;
}

/**
 * Item in *Aperitivo → Default → Primary → Falafel*
 */
export interface AperitivoSliceDefaultPrimaryFalafelItem {
  /**
   * Nome falafel field in *Aperitivo → Default → Primary → Falafel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.falafel[].nome_falafel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_falafel: prismic.KeyTextField;

  /**
   * Vegetariano field in *Aperitivo → Default → Primary → Falafel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.falafel[].vegetariano
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vegetariano: prismic.ImageField<never>;
}

/**
 * Primary content in *Aperitivo → Default → Primary*
 */
export interface AperitivoSliceDefaultPrimary {
  /**
   * Titolo field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Immagine top sx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_top_sx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_sx: prismic.ImageField<never>;

  /**
   * Immagine top dx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_top_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_dx: prismic.ImageField<never>;

  /**
   * Immagine bottom sx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_bottom_sx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_sx: prismic.ImageField<never>;

  /**
   * Immagine bottom dx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_bottom_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_dx: prismic.ImageField<never>;

  /**
   * Sottotitolo field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.sottotitolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sottotitolo: prismic.KeyTextField;

  /**
   * Testo bevande field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.testo_bevande
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_bevande: prismic.KeyTextField;

  /**
   * Bevande field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.nome_bevanda[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nome_bevanda: prismic.GroupField<
    Simplify<AperitivoSliceDefaultPrimaryNomeBevandaItem>
  >;

  /**
   * Testo salsa field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.testo_salsa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_salsa: prismic.KeyTextField;

  /**
   * Salse field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.salse[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  salse: prismic.GroupField<Simplify<AperitivoSliceDefaultPrimarySalseItem>>;

  /**
   * Falafel field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.falafel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  falafel: prismic.GroupField<
    Simplify<AperitivoSliceDefaultPrimaryFalafelItem>
  >;

  /**
   * Pane field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.pane
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pane: prismic.KeyTextField;

  /**
   * Prezzo field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.prezzo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo: prismic.KeyTextField;
}

/**
 * Default variation for Aperitivo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AperitivoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AperitivoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Aperitivo*
 */
type AperitivoSliceVariation = AperitivoSliceDefault;

/**
 * Aperitivo Shared Slice
 *
 * - **API ID**: `aperitivo`
 * - **Description**: Aperitivo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AperitivoSlice = prismic.SharedSlice<
  "aperitivo",
  AperitivoSliceVariation
>;

/**
 * Item in *Bevande → Default → Primary → Bevanda*
 */
export interface BevandeSliceDefaultPrimaryBevandaItem {
  /**
   * Nome field in *Bevande → Default → Primary → Bevanda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.default.primary.bevanda[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Prezzo field in *Bevande → Default → Primary → Bevanda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.default.primary.bevanda[].prezzo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo: prismic.KeyTextField;

  /**
   * Dettagli field in *Bevande → Default → Primary → Bevanda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.default.primary.bevanda[].dettagli
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dettagli: prismic.KeyTextField;
}

/**
 * Primary content in *Bevande → Default → Primary*
 */
export interface BevandeSliceDefaultPrimary {
  /**
   * Immagine bevande field in *Bevande → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.default.primary.immagine_bevande
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bevande: prismic.ImageField<never>;

  /**
   * Titolo bevande field in *Bevande → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.default.primary.titolo_bevande
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_bevande: prismic.KeyTextField;

  /**
   * Bevanda field in *Bevande → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bevande.default.primary.bevanda[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bevanda: prismic.GroupField<Simplify<BevandeSliceDefaultPrimaryBevandaItem>>;
}

/**
 * Default variation for Bevande Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BevandeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BevandeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bevande*
 */
type BevandeSliceVariation = BevandeSliceDefault;

/**
 * Bevande Shared Slice
 *
 * - **API ID**: `bevande`
 * - **Description**: Bevande
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BevandeSlice = prismic.SharedSlice<
  "bevande",
  BevandeSliceVariation
>;

/**
 * Item in *Birre → Default → Primary → Birre*
 */
export interface BirreSliceDefaultPrimaryBirreItem {
  /**
   * Nome field in *Birre → Default → Primary → Birre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.birre[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Prezzo piccolo field in *Birre → Default → Primary → Birre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.birre[].prezzo_piccolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo_piccolo: prismic.KeyTextField;

  /**
   * Prezzo grande field in *Birre → Default → Primary → Birre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.birre[].prezzo_grande
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo_grande: prismic.KeyTextField;

  /**
   * Info field in *Birre → Default → Primary → Birre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.birre[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *Birre → Default → Primary*
 */
export interface BirreSliceDefaultPrimary {
  /**
   * Icona piccola field in *Birre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.icona_piccola
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona_piccola: prismic.ImageField<never>;

  /**
   * Icona grande field in *Birre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.icona_grande
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona_grande: prismic.ImageField<never>;

  /**
   * Birre field in *Birre → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: birre.default.primary.birre[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  birre: prismic.GroupField<Simplify<BirreSliceDefaultPrimaryBirreItem>>;
}

/**
 * Default variation for Birre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BirreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BirreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Birre*
 */
type BirreSliceVariation = BirreSliceDefault;

/**
 * Birre Shared Slice
 *
 * - **API ID**: `birre`
 * - **Description**: Birre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BirreSlice = prismic.SharedSlice<"birre", BirreSliceVariation>;

/**
 * Primary content in *BirreInfo → Default → Primary*
 */
export interface BirreInfoSliceDefaultPrimary {
  /**
   * Titolo field in *BirreInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: birre_info.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Disclaimer field in *BirreInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: birre_info.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  disclaimer: prismic.KeyTextField;
}

/**
 * Default variation for BirreInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BirreInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BirreInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BirreInfo*
 */
type BirreInfoSliceVariation = BirreInfoSliceDefault;

/**
 * BirreInfo Shared Slice
 *
 * - **API ID**: `birre_info`
 * - **Description**: BirreInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BirreInfoSlice = prismic.SharedSlice<
  "birre_info",
  BirreInfoSliceVariation
>;

/**
 * Item in *ConclusioneMenu → Default → Primary → Altre info*
 */
export interface ConclusioneMenuSliceDefaultPrimaryAltreInfoItem {
  /**
   * Info field in *ConclusioneMenu → Default → Primary → Altre info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conclusione_menu.default.primary.altre_info[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *ConclusioneMenu → Default → Primary*
 */
export interface ConclusioneMenuSliceDefaultPrimary {
  /**
   * Coperto field in *ConclusioneMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conclusione_menu.default.primary.coperto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coperto: prismic.KeyTextField;

  /**
   * Altre info field in *ConclusioneMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: conclusione_menu.default.primary.altre_info[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  altre_info: prismic.GroupField<
    Simplify<ConclusioneMenuSliceDefaultPrimaryAltreInfoItem>
  >;
}

/**
 * Default variation for ConclusioneMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConclusioneMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConclusioneMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ConclusioneMenu*
 */
type ConclusioneMenuSliceVariation = ConclusioneMenuSliceDefault;

/**
 * ConclusioneMenu Shared Slice
 *
 * - **API ID**: `conclusione_menu`
 * - **Description**: ConclusioneMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConclusioneMenuSlice = prismic.SharedSlice<
  "conclusione_menu",
  ConclusioneMenuSliceVariation
>;

/**
 * Item in *DrinkList → Default → Primary → Cocktail*
 */
export interface DrinkListSliceDefaultPrimaryCocktailItem {
  /**
   * Nome drink field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[].nome_drink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_drink: prismic.KeyTextField;

  /**
   * Ingredienti field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[].ingredienti
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ingredienti: prismic.KeyTextField;

  /**
   * Prezzo field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[].prezzo
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  prezzo: prismic.NumberField;

  /**
   * Iconcina field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: drink_list.default.primary.cocktail[].iconcina
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  iconcina: prismic.BooleanField;
}

/**
 * Primary content in *DrinkList → Default → Primary*
 */
export interface DrinkListSliceDefaultPrimary {
  /**
   * Titolo field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Testo field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Cocktail field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cocktail: prismic.GroupField<
    Simplify<DrinkListSliceDefaultPrimaryCocktailItem>
  >;

  /**
   * Immagine top sx field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.immagine_top_sx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_sx: prismic.ImageField<never>;

  /**
   * Immagine top mid field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.immagine_top_mid
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_mid: prismic.ImageField<never>;

  /**
   * Immagine top dx field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.immagine_top_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_dx: prismic.ImageField<never>;

  /**
   * Immagine bottom sx field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.immagine_bottom_sx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_sx: prismic.ImageField<never>;

  /**
   * Immagine bottom mid field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.immagine_bottom_mid
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_mid: prismic.ImageField<never>;

  /**
   * Immagine bottom dx field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.immagine_bottom_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_dx: prismic.ImageField<never>;
}

/**
 * Default variation for DrinkList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DrinkListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DrinkListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DrinkList*
 */
type DrinkListSliceVariation = DrinkListSliceDefault;

/**
 * DrinkList Shared Slice
 *
 * - **API ID**: `drink_list`
 * - **Description**: DrinkList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DrinkListSlice = prismic.SharedSlice<
  "drink_list",
  DrinkListSliceVariation
>;

/**
 * Item in *Feroza → Default → Primary → Sezioni*
 */
export interface FerozaSliceDefaultPrimarySezioniItem {
  /**
   * Immagine field in *Feroza → Default → Primary → Sezioni*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.default.primary.sezioni[].immagine
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine: prismic.ImageField<never>;

  /**
   * Testo field in *Feroza → Default → Primary → Sezioni*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.default.primary.sezioni[].testo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo: prismic.RichTextField;
}

/**
 * Primary content in *Feroza → Default → Primary*
 */
export interface FerozaSliceDefaultPrimary {
  /**
   * Sezioni field in *Feroza → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.default.primary.sezioni[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sezioni: prismic.GroupField<Simplify<FerozaSliceDefaultPrimarySezioniItem>>;
}

/**
 * Default variation for Feroza Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FerozaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FerozaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feroza*
 */
type FerozaSliceVariation = FerozaSliceDefault;

/**
 * Feroza Shared Slice
 *
 * - **API ID**: `feroza`
 * - **Description**: Feroza
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FerozaSlice = prismic.SharedSlice<"feroza", FerozaSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Immagine background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.immagine_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_background: prismic.ImageField<never>;

  /**
   * Testo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Spiega field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.spiega
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega: prismic.KeyTextField;

  /**
   * Testo tasto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *InfoFinaliBirreVino → Default → Primary → Info*
 */
export interface InfoFinaliBirreVinoSliceDefaultPrimaryInfoItem {
  /**
   * Testo field in *InfoFinaliBirreVino → Default → Primary → Info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_finali_birre_vino.default.primary.info[].testo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo: prismic.RichTextField;

  /**
   * Immagine field in *InfoFinaliBirreVino → Default → Primary → Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_finali_birre_vino.default.primary.info[].immagine
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine: prismic.ImageField<never>;
}

/**
 * Primary content in *InfoFinaliBirreVino → Default → Primary*
 */
export interface InfoFinaliBirreVinoSliceDefaultPrimary {
  /**
   * Info field in *InfoFinaliBirreVino → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_finali_birre_vino.default.primary.info[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  info: prismic.GroupField<
    Simplify<InfoFinaliBirreVinoSliceDefaultPrimaryInfoItem>
  >;

  /**
   * Chiusa field in *InfoFinaliBirreVino → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_finali_birre_vino.default.primary.chiusa
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  chiusa: prismic.RichTextField;
}

/**
 * Default variation for InfoFinaliBirreVino Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoFinaliBirreVinoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoFinaliBirreVinoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoFinaliBirreVino*
 */
type InfoFinaliBirreVinoSliceVariation = InfoFinaliBirreVinoSliceDefault;

/**
 * InfoFinaliBirreVino Shared Slice
 *
 * - **API ID**: `info_finali_birre_vino`
 * - **Description**: InfoFinaliBirreVino
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoFinaliBirreVinoSlice = prismic.SharedSlice<
  "info_finali_birre_vino",
  InfoFinaliBirreVinoSliceVariation
>;

/**
 * Item in *InfoFooter → Default → Primary → Orari*
 */
export interface InfoFooterSliceDefaultPrimaryOrariItem {
  /**
   * Giorno field in *InfoFooter → Default → Primary → Orari*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.orari[].giorno
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  giorno: prismic.KeyTextField;

  /**
   * Orari field in *InfoFooter → Default → Primary → Orari*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.orari[].orari
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  orari: prismic.KeyTextField;
}

/**
 * Item in *InfoFooter → Default → Primary → Social*
 */
export interface InfoFooterSliceDefaultPrimarySocialItem {
  /**
   * Logo field in *InfoFooter → Default → Primary → Social*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.social[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *InfoFooter → Default → Primary → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *InfoFooter → Default → Primary*
 */
export interface InfoFooterSliceDefaultPrimary {
  /**
   * Nome ristorante field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.nome_ristorante
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_ristorante: prismic.KeyTextField;

  /**
   * Indirizzo field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.indirizzo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  indirizzo: prismic.KeyTextField;

  /**
   * Link a mappa field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.link_mappa
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_mappa: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Titolo orari field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.titolo_orari
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_orari: prismic.KeyTextField;

  /**
   * Orari field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.orari[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  orari: prismic.GroupField<Simplify<InfoFooterSliceDefaultPrimaryOrariItem>>;

  /**
   * Seguici field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.seguici
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seguici: prismic.KeyTextField;

  /**
   * Social field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<InfoFooterSliceDefaultPrimarySocialItem>>;

  /**
   * Riservare tavolo field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.riservare_tavolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  riservare_tavolo: prismic.KeyTextField;

  /**
   * Testo tasto field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Info field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Credits field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.credits
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credits: prismic.KeyTextField;

  /**
   * Link credits field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.link_credits
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_credits: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for InfoFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoFooter*
 */
type InfoFooterSliceVariation = InfoFooterSliceDefault;

/**
 * InfoFooter Shared Slice
 *
 * - **API ID**: `info_footer`
 * - **Description**: InfoFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoFooterSlice = prismic.SharedSlice<
  "info_footer",
  InfoFooterSliceVariation
>;

/**
 * Item in *InfoPiattoMulti → Default → Primary → InfoPiattoMulti*
 */
export interface InfoPiattoMultiSliceDefaultPrimaryInfopiattomultiItem {
  /**
   * Testo field in *InfoPiattoMulti → Default → Primary → InfoPiattoMulti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_piatto_multi.default.primary.infopiattomulti[].testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Bold field in *InfoPiattoMulti → Default → Primary → InfoPiattoMulti*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: info_piatto_multi.default.primary.infopiattomulti[].bold
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bold: prismic.BooleanField;

  /**
   * Small field in *InfoPiattoMulti → Default → Primary → InfoPiattoMulti*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: info_piatto_multi.default.primary.infopiattomulti[].small
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  small: prismic.BooleanField;
}

/**
 * Primary content in *InfoPiattoMulti → Default → Primary*
 */
export interface InfoPiattoMultiSliceDefaultPrimary {
  /**
   * InfoPiattoMulti field in *InfoPiattoMulti → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_piatto_multi.default.primary.infopiattomulti[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  infopiattomulti: prismic.GroupField<
    Simplify<InfoPiattoMultiSliceDefaultPrimaryInfopiattomultiItem>
  >;
}

/**
 * Default variation for InfoPiattoMulti Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoPiattoMultiSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoPiattoMultiSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoPiattoMulti*
 */
type InfoPiattoMultiSliceVariation = InfoPiattoMultiSliceDefault;

/**
 * InfoPiattoMulti Shared Slice
 *
 * - **API ID**: `info_piatto_multi`
 * - **Description**: InfoPiattoMulti
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoPiattoMultiSlice = prismic.SharedSlice<
  "info_piatto_multi",
  InfoPiattoMultiSliceVariation
>;

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * Logo field in *Logo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

/**
 * Item in *Menu → Default → Primary → Voci menu*
 */
export interface MenuSliceDefaultPrimaryVociMenuItem {
  /**
   * Testo field in *Menu → Default → Primary → Voci menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[].testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Link field in *Menu → Default → Primary → Voci menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Menu → Default → Primary*
 */
export interface MenuSliceDefaultPrimary {
  /**
   * Voci menu field in *Menu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  voci_menu: prismic.GroupField<Simplify<MenuSliceDefaultPrimaryVociMenuItem>>;
}

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<"menu", MenuSliceVariation>;

/**
 * Item in *NavigazioneMenu → Default → Primary → NavigazioneMenu*
 */
export interface NavigazioneMenuSliceDefaultPrimaryNavigazionemenuItem {
  /**
   * Titolo field in *NavigazioneMenu → Default → Primary → NavigazioneMenu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigazione_menu.default.primary.navigazionemenu[].titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Icona field in *NavigazioneMenu → Default → Primary → NavigazioneMenu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigazione_menu.default.primary.navigazionemenu[].icona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona: prismic.ImageField<never>;

  /**
   * Link field in *NavigazioneMenu → Default → Primary → NavigazioneMenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigazione_menu.default.primary.navigazionemenu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *NavigazioneMenu → Default → Primary*
 */
export interface NavigazioneMenuSliceDefaultPrimary {
  /**
   * NavigazioneMenu field in *NavigazioneMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigazione_menu.default.primary.navigazionemenu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigazionemenu: prismic.GroupField<
    Simplify<NavigazioneMenuSliceDefaultPrimaryNavigazionemenuItem>
  >;
}

/**
 * Default variation for NavigazioneMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigazioneMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigazioneMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigazioneMenu*
 */
type NavigazioneMenuSliceVariation = NavigazioneMenuSliceDefault;

/**
 * NavigazioneMenu Shared Slice
 *
 * - **API ID**: `navigazione_menu`
 * - **Description**: NavigazioneMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigazioneMenuSlice = prismic.SharedSlice<
  "navigazione_menu",
  NavigazioneMenuSliceVariation
>;

/**
 * Primary content in *PrenotaTavolo → Default → Primary*
 */
export interface PrenotaTavoloSliceDefaultPrimary {
  /**
   * Titolo field in *PrenotaTavolo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prenota_tavolo.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Spiega field in *PrenotaTavolo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prenota_tavolo.default.primary.spiega
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega: prismic.KeyTextField;

  /**
   * Testo tasto field in *PrenotaTavolo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prenota_tavolo.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *PrenotaTavolo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: prenota_tavolo.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Immagine top dx field in *PrenotaTavolo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prenota_tavolo.default.primary.immagine_top_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_dx: prismic.ImageField<never>;
}

/**
 * Default variation for PrenotaTavolo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrenotaTavoloSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrenotaTavoloSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrenotaTavolo*
 */
type PrenotaTavoloSliceVariation = PrenotaTavoloSliceDefault;

/**
 * PrenotaTavolo Shared Slice
 *
 * - **API ID**: `prenota_tavolo`
 * - **Description**: PrenotaTavolo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrenotaTavoloSlice = prismic.SharedSlice<
  "prenota_tavolo",
  PrenotaTavoloSliceVariation
>;

/**
 * Item in *RipetibileMenu → Default → Primary → Elementi menu*
 */
export interface RipetibileMenuSliceDefaultPrimaryElementiMenuItem {
  /**
   * Nome cibo field in *RipetibileMenu → Default → Primary → Elementi menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[].nome_cibo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_cibo: prismic.KeyTextField;

  /**
   * Prezzo cibo field in *RipetibileMenu → Default → Primary → Elementi menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[].prezzo_cibo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo_cibo: prismic.KeyTextField;

  /**
   * Traduzione cibo field in *RipetibileMenu → Default → Primary → Elementi menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[].traduzione_cibo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  traduzione_cibo: prismic.KeyTextField;

  /**
   * Descrizione cibo field in *RipetibileMenu → Default → Primary → Elementi menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[].descrizione_cibo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descrizione_cibo: prismic.KeyTextField;

  /**
   * Vegetariano field in *RipetibileMenu → Default → Primary → Elementi menu*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[].vegetariano
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  vegetariano: prismic.BooleanField;

  /**
   * Piccante field in *RipetibileMenu → Default → Primary → Elementi menu*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[].piccante
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  piccante: prismic.BooleanField;
}

/**
 * Primary content in *RipetibileMenu → Default → Primary*
 */
export interface RipetibileMenuSliceDefaultPrimary {
  /**
   * Titolo sezione field in *RipetibileMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.titolosezione
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolosezione: prismic.KeyTextField;

  /**
   * Immagine sezione field in *RipetibileMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.immagine_sezione
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_sezione: prismic.ImageField<never>;

  /**
   * Traduzione titolo field in *RipetibileMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.traduzione_titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  traduzione_titolo: prismic.KeyTextField;

  /**
   * Elementi menu field in *RipetibileMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ripetibile_menu.default.primary.elementi_menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  elementi_menu: prismic.GroupField<
    Simplify<RipetibileMenuSliceDefaultPrimaryElementiMenuItem>
  >;
}

/**
 * Default variation for RipetibileMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RipetibileMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RipetibileMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RipetibileMenu*
 */
type RipetibileMenuSliceVariation = RipetibileMenuSliceDefault;

/**
 * RipetibileMenu Shared Slice
 *
 * - **API ID**: `ripetibile_menu`
 * - **Description**: RipetibileMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RipetibileMenuSlice = prismic.SharedSlice<
  "ripetibile_menu",
  RipetibileMenuSliceVariation
>;

/**
 * Item in *SezioniHome → Default → Primary → Sezioni home*
 */
export interface SezioniHomeSliceDefaultPrimarySezioniHomeItem {
  /**
   * Titolo field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Foto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;

  /**
   * Spiega servizio field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].spiega_servizio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega_servizio: prismic.KeyTextField;

  /**
   * Disegnino field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].disegnino
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  disegnino: prismic.ImageField<never>;

  /**
   * Testo tasto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Testo a sinistra field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].testo_a_sinistra
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  testo_a_sinistra: prismic.BooleanField;
}

/**
 * Primary content in *SezioniHome → Default → Primary*
 */
export interface SezioniHomeSliceDefaultPrimary {
  /**
   * Sezioni home field in *SezioniHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sezioni_home: prismic.GroupField<
    Simplify<SezioniHomeSliceDefaultPrimarySezioniHomeItem>
  >;
}

/**
 * Default variation for SezioniHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SezioniHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SezioniHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SezioniHome*
 */
type SezioniHomeSliceVariation = SezioniHomeSliceDefault;

/**
 * SezioniHome Shared Slice
 *
 * - **API ID**: `sezioni_home`
 * - **Description**: SezioniHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SezioniHomeSlice = prismic.SharedSlice<
  "sezioni_home",
  SezioniHomeSliceVariation
>;

/**
 * Item in *Simurgh → Default → Primary → Sezioni*
 */
export interface SimurghSliceDefaultPrimarySezioniItem {
  /**
   * Immagine field in *Simurgh → Default → Primary → Sezioni*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simurgh.default.primary.sezioni[].immagine
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine: prismic.ImageField<never>;

  /**
   * Testo field in *Simurgh → Default → Primary → Sezioni*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simurgh.default.primary.sezioni[].testo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo: prismic.RichTextField;
}

/**
 * Primary content in *Simurgh → Default → Primary*
 */
export interface SimurghSliceDefaultPrimary {
  /**
   * Sezioni field in *Simurgh → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: simurgh.default.primary.sezioni[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sezioni: prismic.GroupField<Simplify<SimurghSliceDefaultPrimarySezioniItem>>;

  /**
   * Immagine absolute top field in *Simurgh → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simurgh.default.primary.immagine_absolute_top
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_absolute_top: prismic.ImageField<never>;

  /**
   * Immagine absolute top center field in *Simurgh → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simurgh.default.primary.immagine_absolute_top_center
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_absolute_top_center: prismic.ImageField<never>;

  /**
   * Immagine absolute bottom field in *Simurgh → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simurgh.default.primary.immagine_absolute_bottom
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_absolute_bottom: prismic.ImageField<never>;
}

/**
 * Default variation for Simurgh Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimurghSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimurghSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Simurgh*
 */
type SimurghSliceVariation = SimurghSliceDefault;

/**
 * Simurgh Shared Slice
 *
 * - **API ID**: `simurgh`
 * - **Description**: Simurgh
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimurghSlice = prismic.SharedSlice<
  "simurgh",
  SimurghSliceVariation
>;

/**
 * Item in *Vini → Default → Primary → Vini*
 */
export interface ViniSliceDefaultPrimaryViniItem {
  /**
   * Nome field in *Vini → Default → Primary → Vini*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.vini[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Prezzo piccolo field in *Vini → Default → Primary → Vini*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.vini[].prezzo_piccolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo_piccolo: prismic.KeyTextField;

  /**
   * Prezzo grande field in *Vini → Default → Primary → Vini*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.vini[].prezzo_grande
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo_grande: prismic.KeyTextField;

  /**
   * Info field in *Vini → Default → Primary → Vini*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.vini[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *Vini → Default → Primary*
 */
export interface ViniSliceDefaultPrimary {
  /**
   * Icona piccola field in *Vini → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.icona_piccola
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona_piccola: prismic.ImageField<never>;

  /**
   * Icona grande field in *Vini → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.icona_grande
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona_grande: prismic.ImageField<never>;

  /**
   * Vini field in *Vini → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vini.default.primary.vini[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  vini: prismic.GroupField<Simplify<ViniSliceDefaultPrimaryViniItem>>;
}

/**
 * Default variation for Vini Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ViniSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ViniSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vini*
 */
type ViniSliceVariation = ViniSliceDefault;

/**
 * Vini Shared Slice
 *
 * - **API ID**: `vini`
 * - **Description**: Vini
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ViniSlice = prismic.SharedSlice<"vini", ViniSliceVariation>;

/**
 * Primary content in *ViniInfo → Default → Primary*
 */
export interface ViniInfoSliceDefaultPrimary {
  /**
   * Titolo field in *ViniInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vini_info.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Disclaimer field in *ViniInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vini_info.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  disclaimer: prismic.KeyTextField;
}

/**
 * Default variation for ViniInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ViniInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ViniInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ViniInfo*
 */
type ViniInfoSliceVariation = ViniInfoSliceDefault;

/**
 * ViniInfo Shared Slice
 *
 * - **API ID**: `vini_info`
 * - **Description**: ViniInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ViniInfoSlice = prismic.SharedSlice<
  "vini_info",
  ViniInfoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AperitivoDocument,
      AperitivoDocumentData,
      AperitivoDocumentDataSlicesSlice,
      BevandeDocument,
      BevandeDocumentData,
      BevandeDocumentDataSlicesSlice,
      BirreDocument,
      BirreDocumentData,
      BirreDocumentDataSlicesSlice,
      ConclusioneMenuDocument,
      ConclusioneMenuDocumentData,
      ConclusioneMenuDocumentDataSlicesSlice,
      ContattiDocument,
      ContattiDocumentData,
      ContattiDocumentDataSlicesSlice,
      DrinklistDocument,
      DrinklistDocumentData,
      DrinklistDocumentDataSlicesSlice,
      FerozaDocument,
      FerozaDocumentData,
      FerozaDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      InfofinalivinobirraDocument,
      InfofinalivinobirraDocumentData,
      InfofinalivinobirraDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataSlicesSlice,
      PiattomultiDocument,
      PiattomultiDocumentData,
      PiattomultiDocumentDataSlicesSlice,
      ViniDocument,
      ViniDocumentData,
      ViniDocumentDataSlicesSlice,
      AllDocumentTypes,
      AperitivoSlice,
      AperitivoSliceDefaultPrimaryNomeBevandaItem,
      AperitivoSliceDefaultPrimarySalseItem,
      AperitivoSliceDefaultPrimaryFalafelItem,
      AperitivoSliceDefaultPrimary,
      AperitivoSliceVariation,
      AperitivoSliceDefault,
      BevandeSlice,
      BevandeSliceDefaultPrimaryBevandaItem,
      BevandeSliceDefaultPrimary,
      BevandeSliceVariation,
      BevandeSliceDefault,
      BirreSlice,
      BirreSliceDefaultPrimaryBirreItem,
      BirreSliceDefaultPrimary,
      BirreSliceVariation,
      BirreSliceDefault,
      BirreInfoSlice,
      BirreInfoSliceDefaultPrimary,
      BirreInfoSliceVariation,
      BirreInfoSliceDefault,
      ConclusioneMenuSlice,
      ConclusioneMenuSliceDefaultPrimaryAltreInfoItem,
      ConclusioneMenuSliceDefaultPrimary,
      ConclusioneMenuSliceVariation,
      ConclusioneMenuSliceDefault,
      DrinkListSlice,
      DrinkListSliceDefaultPrimaryCocktailItem,
      DrinkListSliceDefaultPrimary,
      DrinkListSliceVariation,
      DrinkListSliceDefault,
      FerozaSlice,
      FerozaSliceDefaultPrimarySezioniItem,
      FerozaSliceDefaultPrimary,
      FerozaSliceVariation,
      FerozaSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InfoFinaliBirreVinoSlice,
      InfoFinaliBirreVinoSliceDefaultPrimaryInfoItem,
      InfoFinaliBirreVinoSliceDefaultPrimary,
      InfoFinaliBirreVinoSliceVariation,
      InfoFinaliBirreVinoSliceDefault,
      InfoFooterSlice,
      InfoFooterSliceDefaultPrimaryOrariItem,
      InfoFooterSliceDefaultPrimarySocialItem,
      InfoFooterSliceDefaultPrimary,
      InfoFooterSliceVariation,
      InfoFooterSliceDefault,
      InfoPiattoMultiSlice,
      InfoPiattoMultiSliceDefaultPrimaryInfopiattomultiItem,
      InfoPiattoMultiSliceDefaultPrimary,
      InfoPiattoMultiSliceVariation,
      InfoPiattoMultiSliceDefault,
      LogoSlice,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
      MenuSlice,
      MenuSliceDefaultPrimaryVociMenuItem,
      MenuSliceDefaultPrimary,
      MenuSliceVariation,
      MenuSliceDefault,
      NavigazioneMenuSlice,
      NavigazioneMenuSliceDefaultPrimaryNavigazionemenuItem,
      NavigazioneMenuSliceDefaultPrimary,
      NavigazioneMenuSliceVariation,
      NavigazioneMenuSliceDefault,
      PrenotaTavoloSlice,
      PrenotaTavoloSliceDefaultPrimary,
      PrenotaTavoloSliceVariation,
      PrenotaTavoloSliceDefault,
      RipetibileMenuSlice,
      RipetibileMenuSliceDefaultPrimaryElementiMenuItem,
      RipetibileMenuSliceDefaultPrimary,
      RipetibileMenuSliceVariation,
      RipetibileMenuSliceDefault,
      SezioniHomeSlice,
      SezioniHomeSliceDefaultPrimarySezioniHomeItem,
      SezioniHomeSliceDefaultPrimary,
      SezioniHomeSliceVariation,
      SezioniHomeSliceDefault,
      SimurghSlice,
      SimurghSliceDefaultPrimarySezioniItem,
      SimurghSliceDefaultPrimary,
      SimurghSliceVariation,
      SimurghSliceDefault,
      ViniSlice,
      ViniSliceDefaultPrimaryViniItem,
      ViniSliceDefaultPrimary,
      ViniSliceVariation,
      ViniSliceDefault,
      ViniInfoSlice,
      ViniInfoSliceDefaultPrimary,
      ViniInfoSliceVariation,
      ViniInfoSliceDefault,
    };
  }
}
