// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FerozaDocumentDataSlicesSlice = SezioniHomeSlice;

/**
 * Content for Feroza documents
 */
interface FerozaDocumentData {
  /**
   * Slice Zone field in *Feroza*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FerozaDocumentDataSlicesSlice> /**
   * Meta Title field in *Feroza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: feroza.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Feroza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: feroza.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Feroza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Feroza document from Prismic
 *
 * - **API ID**: `feroza`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FerozaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FerozaDocumentData>,
    "feroza",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = MenuSlice | LogoSlice;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

export type AllDocumentTypes = FerozaDocument | HeaderDocument;

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

/**
 * Item in *Menu → Default → Primary → Voci menu*
 */
export interface MenuSliceDefaultPrimaryVociMenuItem {
  /**
   * Testo field in *Menu → Default → Primary → Voci menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[].testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Link field in *Menu → Default → Primary → Voci menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Menu → Default → Primary*
 */
export interface MenuSliceDefaultPrimary {
  /**
   * Voci menu field in *Menu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  voci_menu: prismic.GroupField<Simplify<MenuSliceDefaultPrimaryVociMenuItem>>;
}

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<"menu", MenuSliceVariation>;

/**
 * Item in *SezioniHome → Default → Primary → Sezioni home*
 */
export interface SezioniHomeSliceDefaultPrimarySezioniHomeItem {
  /**
   * Titolo field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Foto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;

  /**
   * Spiega servizio field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].spiega_servizio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega_servizio: prismic.KeyTextField;

  /**
   * Disegnino field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].disegnino
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  disegnino: prismic.ImageField<never>;

  /**
   * Testo tasto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;
}

/**
 * Primary content in *SezioniHome → Default → Primary*
 */
export interface SezioniHomeSliceDefaultPrimary {
  /**
   * Sezioni home field in *SezioniHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sezioni_home: prismic.GroupField<
    Simplify<SezioniHomeSliceDefaultPrimarySezioniHomeItem>
  >;

  /**
   * Link tasto field in *SezioniHome → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SezioniHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SezioniHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SezioniHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SezioniHome*
 */
type SezioniHomeSliceVariation = SezioniHomeSliceDefault;

/**
 * SezioniHome Shared Slice
 *
 * - **API ID**: `sezioni_home`
 * - **Description**: SezioniHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SezioniHomeSlice = prismic.SharedSlice<
  "sezioni_home",
  SezioniHomeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FerozaDocument,
      FerozaDocumentData,
      FerozaDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      AllDocumentTypes,
      LogoSlice,
      LogoSliceVariation,
      LogoSliceDefault,
      MenuSlice,
      MenuSliceDefaultPrimaryVociMenuItem,
      MenuSliceDefaultPrimary,
      MenuSliceVariation,
      MenuSliceDefault,
      SezioniHomeSlice,
      SezioniHomeSliceDefaultPrimarySezioniHomeItem,
      SezioniHomeSliceDefaultPrimary,
      SezioniHomeSliceVariation,
      SezioniHomeSliceDefault,
    };
  }
}
