// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AperitivoDocumentDataSlicesSlice = AperitivoSlice;

/**
 * Content for Aperitivo documents
 */
interface AperitivoDocumentData {
  /**
   * Slice Zone field in *Aperitivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AperitivoDocumentDataSlicesSlice>;
}

/**
 * Aperitivo document from Prismic
 *
 * - **API ID**: `aperitivo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AperitivoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AperitivoDocumentData>,
    "aperitivo",
    Lang
  >;

type DrinklistDocumentDataSlicesSlice = DrinkListSlice;

/**
 * Content for DrinkList documents
 */
interface DrinklistDocumentData {
  /**
   * Slice Zone field in *DrinkList*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: drinklist.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DrinklistDocumentDataSlicesSlice>;
}

/**
 * DrinkList document from Prismic
 *
 * - **API ID**: `drinklist`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DrinklistDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DrinklistDocumentData>,
    "drinklist",
    Lang
  >;

type FerozaDocumentDataSlicesSlice = HeroSlice | SezioniHomeSlice;

/**
 * Content for Feroza documents
 */
interface FerozaDocumentData {
  /**
   * Slice Zone field in *Feroza*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FerozaDocumentDataSlicesSlice> /**
   * Meta Title field in *Feroza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: feroza.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Feroza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: feroza.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Feroza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feroza.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Feroza document from Prismic
 *
 * - **API ID**: `feroza`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FerozaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FerozaDocumentData>, "feroza", Lang>;

type FooterDocumentDataSlicesSlice = LogoSlice | InfoFooterSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = MenuSlice | LogoSlice;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

export type AllDocumentTypes =
  | AperitivoDocument
  | DrinklistDocument
  | FerozaDocument
  | FooterDocument
  | HeaderDocument;

/**
 * Item in *Aperitivo → Default → Primary → Bevande*
 */
export interface AperitivoSliceDefaultPrimaryNomeBevandaItem {
  /**
   * Nome bevanda field in *Aperitivo → Default → Primary → Bevande*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.nome_bevanda[].nome_bevanda
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_bevanda: prismic.KeyTextField;

  /**
   * Icona field in *Aperitivo → Default → Primary → Bevande*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.nome_bevanda[].icona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icona: prismic.ImageField<never>;
}

/**
 * Item in *Aperitivo → Default → Primary → Salse*
 */
export interface AperitivoSliceDefaultPrimarySalseItem {
  /**
   * Nome salsa field in *Aperitivo → Default → Primary → Salse*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.salse[].nome_salsa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_salsa: prismic.KeyTextField;

  /**
   * Vegetariano field in *Aperitivo → Default → Primary → Salse*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.salse[].vegetariano
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vegetariano: prismic.ImageField<never>;
}

/**
 * Item in *Aperitivo → Default → Primary → Falafel*
 */
export interface AperitivoSliceDefaultPrimaryFalafelItem {
  /**
   * Nome falafel field in *Aperitivo → Default → Primary → Falafel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.falafel[].nome_falafel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_falafel: prismic.KeyTextField;

  /**
   * Vegetariano field in *Aperitivo → Default → Primary → Falafel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.falafel[].vegetariano
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vegetariano: prismic.ImageField<never>;
}

/**
 * Primary content in *Aperitivo → Default → Primary*
 */
export interface AperitivoSliceDefaultPrimary {
  /**
   * Titolo field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Immagine top sx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_top_sx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_sx: prismic.ImageField<never>;

  /**
   * Immagine top dx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_top_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_top_dx: prismic.ImageField<never>;

  /**
   * Immagine bottom sx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_bottom_sx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_sx: prismic.ImageField<never>;

  /**
   * Immagine bottom dx field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.immagine_bottom_dx
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_bottom_dx: prismic.ImageField<never>;

  /**
   * Sottotitolo field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.sottotitolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sottotitolo: prismic.KeyTextField;

  /**
   * Testo bevande field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.testo_bevande
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_bevande: prismic.KeyTextField;

  /**
   * Bevande field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.nome_bevanda[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nome_bevanda: prismic.GroupField<
    Simplify<AperitivoSliceDefaultPrimaryNomeBevandaItem>
  >;

  /**
   * Testo salsa field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.testo_salsa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_salsa: prismic.KeyTextField;

  /**
   * Salse field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.salse[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  salse: prismic.GroupField<Simplify<AperitivoSliceDefaultPrimarySalseItem>>;

  /**
   * Falafel field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.falafel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  falafel: prismic.GroupField<
    Simplify<AperitivoSliceDefaultPrimaryFalafelItem>
  >;

  /**
   * Pane field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.pane
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pane: prismic.KeyTextField;

  /**
   * Prezzo field in *Aperitivo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aperitivo.default.primary.prezzo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prezzo: prismic.KeyTextField;
}

/**
 * Default variation for Aperitivo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AperitivoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AperitivoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Aperitivo*
 */
type AperitivoSliceVariation = AperitivoSliceDefault;

/**
 * Aperitivo Shared Slice
 *
 * - **API ID**: `aperitivo`
 * - **Description**: Aperitivo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AperitivoSlice = prismic.SharedSlice<
  "aperitivo",
  AperitivoSliceVariation
>;

/**
 * Item in *DrinkList → Default → Primary → Cocktail*
 */
export interface DrinkListSliceDefaultPrimaryCocktailItem {
  /**
   * Nome drink field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[].nome_drink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_drink: prismic.KeyTextField;

  /**
   * Ingredienti field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[].ingredienti
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ingredienti: prismic.KeyTextField;

  /**
   * Prezzo field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[].prezzo
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  prezzo: prismic.NumberField;

  /**
   * Iconcina field in *DrinkList → Default → Primary → Cocktail*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: drink_list.default.primary.cocktail[].iconcina
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  iconcina: prismic.BooleanField;
}

/**
 * Primary content in *DrinkList → Default → Primary*
 */
export interface DrinkListSliceDefaultPrimary {
  /**
   * Titolo field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Testo field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Cocktail field in *DrinkList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: drink_list.default.primary.cocktail[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cocktail: prismic.GroupField<
    Simplify<DrinkListSliceDefaultPrimaryCocktailItem>
  >;
}

/**
 * Default variation for DrinkList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DrinkListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DrinkListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DrinkList*
 */
type DrinkListSliceVariation = DrinkListSliceDefault;

/**
 * DrinkList Shared Slice
 *
 * - **API ID**: `drink_list`
 * - **Description**: DrinkList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DrinkListSlice = prismic.SharedSlice<
  "drink_list",
  DrinkListSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Immagine background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.immagine_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_background: prismic.ImageField<never>;

  /**
   * Testo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Spiega field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.spiega
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega: prismic.KeyTextField;

  /**
   * Testo tasto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *InfoFooter → Default → Primary → Orari*
 */
export interface InfoFooterSliceDefaultPrimaryOrariItem {
  /**
   * Giorno field in *InfoFooter → Default → Primary → Orari*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.orari[].giorno
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  giorno: prismic.KeyTextField;

  /**
   * Orari field in *InfoFooter → Default → Primary → Orari*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.orari[].orari
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  orari: prismic.KeyTextField;
}

/**
 * Item in *InfoFooter → Default → Primary → Social*
 */
export interface InfoFooterSliceDefaultPrimarySocialItem {
  /**
   * Logo field in *InfoFooter → Default → Primary → Social*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.social[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *InfoFooter → Default → Primary → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *InfoFooter → Default → Primary*
 */
export interface InfoFooterSliceDefaultPrimary {
  /**
   * Nome ristorante field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.nome_ristorante
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_ristorante: prismic.KeyTextField;

  /**
   * Indirizzo field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.indirizzo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  indirizzo: prismic.KeyTextField;

  /**
   * Link a mappa field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.link_mappa
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_mappa: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Titolo orari field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.titolo_orari
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_orari: prismic.KeyTextField;

  /**
   * Orari field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.orari[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  orari: prismic.GroupField<Simplify<InfoFooterSliceDefaultPrimaryOrariItem>>;

  /**
   * Seguici field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.seguici
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seguici: prismic.KeyTextField;

  /**
   * Social field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<InfoFooterSliceDefaultPrimarySocialItem>>;

  /**
   * Riservare tavolo field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.riservare_tavolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  riservare_tavolo: prismic.KeyTextField;

  /**
   * Testo tasto field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Info field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Credits field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.credits
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credits: prismic.KeyTextField;

  /**
   * Link credits field in *InfoFooter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_footer.default.primary.link_credits
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_credits: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for InfoFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoFooter*
 */
type InfoFooterSliceVariation = InfoFooterSliceDefault;

/**
 * InfoFooter Shared Slice
 *
 * - **API ID**: `info_footer`
 * - **Description**: InfoFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoFooterSlice = prismic.SharedSlice<
  "info_footer",
  InfoFooterSliceVariation
>;

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * Logo field in *Logo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

/**
 * Item in *Menu → Default → Primary → Voci menu*
 */
export interface MenuSliceDefaultPrimaryVociMenuItem {
  /**
   * Testo field in *Menu → Default → Primary → Voci menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[].testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Link field in *Menu → Default → Primary → Voci menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Menu → Default → Primary*
 */
export interface MenuSliceDefaultPrimary {
  /**
   * Voci menu field in *Menu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.voci_menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  voci_menu: prismic.GroupField<Simplify<MenuSliceDefaultPrimaryVociMenuItem>>;
}

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<"menu", MenuSliceVariation>;

/**
 * Item in *SezioniHome → Default → Primary → Sezioni home*
 */
export interface SezioniHomeSliceDefaultPrimarySezioniHomeItem {
  /**
   * Titolo field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Foto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;

  /**
   * Spiega servizio field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].spiega_servizio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega_servizio: prismic.KeyTextField;

  /**
   * Disegnino field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].disegnino
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  disegnino: prismic.ImageField<never>;

  /**
   * Testo tasto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Testo a sinistra field in *SezioniHome → Default → Primary → Sezioni home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[].testo_a_sinistra
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  testo_a_sinistra: prismic.BooleanField;
}

/**
 * Primary content in *SezioniHome → Default → Primary*
 */
export interface SezioniHomeSliceDefaultPrimary {
  /**
   * Sezioni home field in *SezioniHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sezioni_home.default.primary.sezioni_home[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sezioni_home: prismic.GroupField<
    Simplify<SezioniHomeSliceDefaultPrimarySezioniHomeItem>
  >;
}

/**
 * Default variation for SezioniHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SezioniHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SezioniHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SezioniHome*
 */
type SezioniHomeSliceVariation = SezioniHomeSliceDefault;

/**
 * SezioniHome Shared Slice
 *
 * - **API ID**: `sezioni_home`
 * - **Description**: SezioniHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SezioniHomeSlice = prismic.SharedSlice<
  "sezioni_home",
  SezioniHomeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AperitivoDocument,
      AperitivoDocumentData,
      AperitivoDocumentDataSlicesSlice,
      DrinklistDocument,
      DrinklistDocumentData,
      DrinklistDocumentDataSlicesSlice,
      FerozaDocument,
      FerozaDocumentData,
      FerozaDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      AllDocumentTypes,
      AperitivoSlice,
      AperitivoSliceDefaultPrimaryNomeBevandaItem,
      AperitivoSliceDefaultPrimarySalseItem,
      AperitivoSliceDefaultPrimaryFalafelItem,
      AperitivoSliceDefaultPrimary,
      AperitivoSliceVariation,
      AperitivoSliceDefault,
      DrinkListSlice,
      DrinkListSliceDefaultPrimaryCocktailItem,
      DrinkListSliceDefaultPrimary,
      DrinkListSliceVariation,
      DrinkListSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InfoFooterSlice,
      InfoFooterSliceDefaultPrimaryOrariItem,
      InfoFooterSliceDefaultPrimarySocialItem,
      InfoFooterSliceDefaultPrimary,
      InfoFooterSliceVariation,
      InfoFooterSliceDefault,
      LogoSlice,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
      MenuSlice,
      MenuSliceDefaultPrimaryVociMenuItem,
      MenuSliceDefaultPrimary,
      MenuSliceVariation,
      MenuSliceDefault,
      SezioniHomeSlice,
      SezioniHomeSliceDefaultPrimarySezioniHomeItem,
      SezioniHomeSliceDefaultPrimary,
      SezioniHomeSliceVariation,
      SezioniHomeSliceDefault,
    };
  }
}
