// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aperitivo: dynamic(() => import("./Aperitivo")),
  bevande: dynamic(() => import("./Bevande")),
  birre: dynamic(() => import("./Birre")),
  birre_info: dynamic(() => import("./BirreInfo")),
  conclusione_menu: dynamic(() => import("./ConclusioneMenu")),
  contatti: dynamic(() => import("./Contatti")),
  drink_list: dynamic(() => import("./DrinkList")),
  feroza: dynamic(() => import("./Feroza")),
  hero: dynamic(() => import("./Hero")),
  info_finali_birre_vino: dynamic(() => import("./InfoFinaliBirreVino")),
  info_footer: dynamic(() => import("./InfoFooter")),
  info_piatto_multi: dynamic(() => import("./InfoPiattoMulti")),
  logo: dynamic(() => import("./Logo")),
  menu: dynamic(() => import("./Menu")),
  navigazione_menu: dynamic(() => import("./NavigazioneMenu")),
  prenota_tavolo: dynamic(() => import("./PrenotaTavolo")),
  ripetibile_menu: dynamic(() => import("./RipetibileMenu")),
  sezioni_home: dynamic(() => import("./SezioniHome")),
  simurgh: dynamic(() => import("./Simurgh")),
  social: dynamic(() => import("./Social")),
  vini: dynamic(() => import("./Vini")),
  vini_info: dynamic(() => import("./ViniInfo")),
};
